# youtube_uploader 13.4.2
import sqlite3, markdown, time, datetime, os, httplib2
import google_auth_oauthlib.flow
import googleapiclient.discovery
import googleapiclient.errors
import google.auth.transport.requests
import os
from threading import TIMEOUT_MAX, Thread
from googleapiclient.http import MediaFileUpload
from video_count import CountHandler
import json
import requests
from send2trash import send2trash

### ### ### ### ### USER STUFF ### ### ### ### ###
###                                            ###

DISPLAY_NAME = "To the Sun"
VIDEOS_PATH = "D:\[Library]\[Video]\[Works]\[Uploads]"
PROJECTS_PATH = "D:\[Library]\[Audio]\[Works]\[Projects]"
CHANNEL_ID = "UCbBI9uyXI4hm3vh9jqMP37g"
USER_PLAYLIST_IDS = [
    "PLS0ekF80gz5_33_ejo17jNDPUZS_OAG2Q",
]


HOUR_INTERVAL = 4               # How many hours to wait between cycles.
MAX_TIMEOUT_ATTEMPTS = 24       # How many retries to give failed API requests.
TIMEOUT_INTERVAL = 5            # How long to wait, in seconds, between retry attempts.
DELETE_REUSED_VIDEOS = True     # Delete videos from disk if they've been uploaded before.
DEBUG_MODE = True               # Allows more print statements to appear.


FULL_BODY_TEXT = (
    #"\nArranged using The Amanuensis, an automated songwriting and recording system "
    #"aimed at ridding the process of anything left-brained, so one need "
    #"never leave a creative, spontaneous and improvisational state of mind, "
    #"from the inception of the song until its final master. The program will "
    #"construct a cohesive song structure, using the best of what you give it, "
    #"looping around you and growing in real-time as you play. All you have to "
    #"do is jam and fully written songs will flow out behind you wherever you go.\n"
    #"\nPull individual stems and collaborate at https://blend.io/tothesun\n"
    "\nThis is a work in progress; each incremental recording is automatically uploaded to "
    "https://www.youtube.com/playlist?list=PLS0ekF80gz5_33_ejo17jNDPUZS_OAG2Q. For finished works "
    "check out https://tothesun.bandcamp.com/. If you want to collaborate on this "
    "song or any other get a hold of me here, at Bandcamp or http://soundcloud.com/to_the_sun/ "
    "and I can get you some stems."
)

LINKS = {
    "Jaybird": "https://d.tube/#!/c/jaybird",
    "Khoaquoi": "https://soundcloud.com/khoaquoi",
    "Proprium": "https://www.youtube.com/@propriumsound",
    "Mark Miller": "https://soundcloud.com/1whitebuffalo",
    "Sound of Unknowing": "https://thesoundofunknowing.bandcamp.com",
    "ÉV": "https://www.youtube.com/@eveofev"
}

CREDITS = {
    "visuals by 777seven_ Thoughts777": "Visuals generated by 777seven_ Thoughts777 (https://www.instagram.com/777seven_thoughts777/)\n",
    "visuals by Andrew's_Art_Project": "Visuals generated by Andrew's_Art_Project (https://www.instagram.com/andrews_art_project/)\n",
    "visuals by Chantelle Ko": "Visuals generated by Chantelle Ko (https://www.youtube.com/user/HighlandViolinist)\n",
    "visuals by oqlrrmusic": "Visuals generated by oqlrrmusic (https://www.instagram.com/oqlrr.music/)\n",
}

###                                            ###
### ### ### ### ### USER STUFF ### ### ### ### ###


# Current script directory.
CWD = os.path.dirname(os.path.realpath(__file__))

# List of different scopes needed for the Youtube API.
SCOPES = [
    "https://www.googleapis.com/auth/youtube.readonly",
    "https://www.googleapis.com/auth/youtube.upload",
    "https://www.googleapis.com/auth/youtube.force-ssl",
    "https://www.googleapis.com/auth/youtube",
]

DISPLAY_NAME = DISPLAY_NAME.lower()     # converts display_name to lowercase

# httplib2.debuglevel = 1     # may help get more detailed http errors
def debug(*args, **kwargs):
    # prints out debug messages when debug mode is on
    if DEBUG_MODE: print(*args, **kwargs)


class UploadBot:
    API_KEY = ""

    def run(self):
        ''' Start bot, setup variables, api, and database, then start main loop. '''
        debug(f'(d) Initializing UploadBot...')
        self.setup()

        while True:                     # main loop (runs main function at launch once before waiting)
            debug(f'(d) Entering self.main...')
            self.main()                 # run main function
            debug(f'(d) Exiting self.main and entering interval...')
            self.wait_for_interval()    # wait for <HOUR_INTERVAL> long interval


    def setup(self):
        ''' Initializes main variables as well as Youtube's API Service and our database. '''
        self.request = google.auth.transport.requests.Request()             # bizarre line required for token refreshing
        self.like_titleId = ['','']
        self.comment_titleIdBody = ['','','']
        self.func = 'setup'

        # Load API key from credentials.json
        credentials_file = os.path.join(CWD, 'credentials.json')
        if os.path.exists(credentials_file):
            try:
                with open(credentials_file, 'r') as f:
                    creds = json.load(f)
                    self.API_KEY = creds.get('api_key', '')
            except Exception as e:
                print(f'Error loading credentials.json: {e}')
                self.API_KEY = ''
        else:
            print(f'credentials.json not found in {CWD}')
            self.API_KEY = ''

        # Disable OAuthlib's HTTPS verification when running locally.
        os.environ["OAUTHLIB_INSECURE_TRANSPORT"] = "0"

        # set up the api variables
        api_service_name = "youtube"
        api_version = "v3"
        client_secrets_file = os.path.join(CWD, 'client_secret.json')       # gets client_secret from script directory

        # Get credentials and create an API client
        flow = google_auth_oauthlib.flow.InstalledAppFlow.from_client_secrets_file(client_secrets_file, SCOPES)     # set up the OAuth flow
        self.credentials = flow.run_local_server()                          # login to gain credentials and tokens

        self.youtube = googleapiclient.discovery.build(api_service_name, api_version, credentials=self.credentials) # init youtube instance
        self.conn = sqlite3.connect(os.path.join(CWD, 'videos_info.db'))    # create/connect to database
        self.cur = self.conn.cursor()                                       # create a cursor to execute database commands
        try: self.cur.execute("""
                CREATE TABLE videos (
                    videoId text,
                    likeCount integer,
                    commentCount integer,
                    used integer,
                    path text,
                    deleted integer,
                    title text,
                    credits text
                )
        """)                                                                # create a table to store all video information
        except sqlite3.OperationalError: pass                               # do nothing if table already exists
        try: self.cur.execute('ALTER TABLE videos ADD COLUMN path text DEFAULT ""')
        except sqlite3.OperationalError: pass                               # attempt to insert new deletion-related columns to table
        try: self.cur.execute('ALTER TABLE videos ADD COLUMN deleted integer DEFAULT 1')
        except sqlite3.OperationalError: pass
        try: self.cur.execute('ALTER TABLE videos ADD COLUMN title text')
        except sqlite3.OperationalError: pass
        try: self.cur.execute('ALTER TABLE videos ADD COLUMN credits text')
        except sqlite3.OperationalError: pass
        self.conn.commit()                                                  # save the data
        debug(f'Initalization complete.\n')


    def main(self, sleep_delay=60):
        self.func = 'main'
        print('Running self.main...')
        try:
            self.delete_videos_from_disk()                                  # attempt to delete any lingering videos
            count = CountHandler(self.youtube, "PLS0ekF80gz5_33_ejo17jNDPUZS_OAG2Q", 999)    # hardcoded ID, not based on playlist list
            count.adjust()                                                  # delete old excess videos
            self.channel_videos = self.get_channel_videos()                 # get list of channel videos for future use
            self.check_for_likes_and_comments()                             # check likes/comments

            self.like_titleId = ['','']
            self.comment_titleIdBody = ['','','']

            disliked_videos = self.get_disliked_videos()        # get disliked videos
            self.delete_videos(disliked_videos)                                   # delete the disliked videos

            # Upload videos to YouTube. Does so in a separate thread as Google's
            # library may have a bug that is keeping video files open after uploading.
            # If it's in a separate thread however, all file-handles will be forcibly
            # closed once the thread terminates, allowing us to delete the videos again.
            try: self.conn.commit()
            except: pass
            upload_thread = Thread(target=self.upload_videos, daemon=True)  # create thread object
            upload_thread.start()                                           # start thread
            while upload_thread.is_alive(): time.sleep(0.25)                # wait for thread to end
            print('Uploading process complete, returning to main loop.')
            self.delete_videos_from_disk()                                  # delete videos
        except Exception as error:
            debug(f'\n(d) MAIN LOOP ({self.func}): {type(error)} {error}')
            print('\nMAIN LOOP ERROR:\n  ', error)
        finally:
            print(f'\nself.main loop complete, sleeping for {sleep_delay} seconds...\n')
            time.sleep(sleep_delay)             # sleep for desired delay (default: 60 sec)


    def wait_for_interval(self):                # pauses program for <HOUR_INTERVAL> long intervals
        now = datetime.datetime.now()
        # only round down if interval is at least one hour
        desiredStartTime = now.replace(minute=0, second=0) if HOUR_INTERVAL >= 1 else now
        desiredEndTime = desiredStartTime + datetime.timedelta(hours=HOUR_INTERVAL)

        realTime = now.strftime('%I:%M %p').lstrip('0')
        realEndTime = desiredEndTime.strftime('%I:%M %p').lstrip('0')
        print(f'\n\nCYCLE COMPLETED AT {realTime}.\nWAITING {HOUR_INTERVAL} HOUR(S).\nNEXT CYCLE STARTS AT {realEndTime}.\n\n')
        while True:
            if datetime.datetime.now() > desiredEndTime:
                time.sleep(TIMEOUT_INTERVAL)    # sleep <TIMEOUT_INTERVAL> seconds in case computer was asleep
                if self.credentials.expired:    # token expired during interval, try to refresh
                    self.attempts = 1
                    self.refresh_token()
                time.sleep(15)                  # sleep ADDITIONAL 15 seconds, just for extra safety
                return                          # it's been approximately <HOUR_INTERVAL> hours
            time.sleep(1)                       # sleep for one second between loops to save resources


    def refresh_token(self):
        ''' Refreshing tokens now uses the timeout-system. '''
        debug('\n(d) Expired token detected. Refreshing...')
        while self.credentials.expired and self.attempts <= MAX_TIMEOUT_ATTEMPTS:   # loop while token is still expired and we have attempts left
            try: return self.credentials.refresh(self.request)                      # attempt to refresh token
            except Exception as error:                                              # failure, use timeout
                debug('(d) REFRESH ERROR:', type(error), error)
                print(f'An unexpected token-refresh error occurred, trying again in {TIMEOUT_INTERVAL} seconds...')
                self.attempts += 1
                time.sleep(TIMEOUT_INTERVAL)
        if self.credentials.expired: return self.credentials.refresh(self.request)  # loop failed + token still expired -> try again and let it raise error


    def delete_videos_from_disk(self, paths=None, conn=None, cur=None):
        conn = conn if conn else self.conn
        cur = cur if cur else self.cur
        if not paths:
            cur.execute('SELECT * FROM videos WHERE deleted=0')
            to_delete = cur.fetchall()
            paths = [video[4] for video in to_delete]
        if not paths: return                                            # return immediately if nothing to delete

        print('\nDeleting videos from disk:')
        for video in paths: print('   ', video)

        for path in paths:                                              # loop over video paths
            try: os.remove(path)                                        # try to delete video path
            except Exception as error:
                debug('(d)', type(error), error)
                print('Video was NOT successfully deleted from disk:', path)
            if not os.path.exists(path):                                # check if the video is gone
                print('Video successfully deleted from disk:', path)
                cur.execute("UPDATE videos SET deleted=1 WHERE path=?", (path,))  # update database
                conn.commit()                                           # save deleted video


    ###########################################################################


    def handle_yt_errors(self, error, func_name, ignore_errors=False):
        debug('\n(d) ERROR:', type(error), error)
        if isinstance(error, googleapiclient.errors.ResumableUploadError):
            try: print(error._get_reason())
            except: print('(!) Unknown ResumableUploadError')
        if 'quota' in str(error).lower():                       # catches all possible quota errors
            if func_name == 'chunk_yt_request': return -1.9     # special error code for skipping uploads
            print(f'Quota reached, sleeping for {HOUR_INTERVAL} hour(s) inside {func_name}.')
            self.wait_for_interval()                            # wait for interval inside error handler
            print(f'Interval complete. Resuming from inside {func_name}.')
        else:
            if self.credentials.expired:                        # check if token expired
                print('An error occurred possibly due to an expired token, refreshing...')
                self.refresh_token()                            # if so, refresh and try again
                return
            if not ignore_errors and self.attempts <= MAX_TIMEOUT_ATTEMPTS:
                print(f'An unexpected error occurred, trying again in {TIMEOUT_INTERVAL} seconds...')
                self.attempts += 1
                time.sleep(TIMEOUT_INTERVAL)
            else:
                print('An unexpected error occured and could not be resolved, giving up.')
                raise error


    ''' The following 3 functions wrap around the youtube api instance (self.youtube)
    in order to ensure that if the quota is reached while calling it, the program
    freezes in place for 4 hours and resumes with the failed youtube api call,
    progressing back through the program as if nothing happened. '''
    def get_yt_request(self, func, kwargs={}, ignore_errors=False):  # gets and returns a request
        self.attempts = 1
        while True:
            debug(f"(d) Getting a YouTube request: '{self.func}' (creating video upload request)")
            try: return func(**kwargs)
            except Exception as error: self.handle_yt_errors(error, 'get_yt_request', ignore_errors)


    def execute_yt_request(self, func, kwargs={}, ignore_errors=False):  # gets, executes, and returns a request
        self.attempts = 1
        while True:
            debug(f"(d) Executing a YouTube request: '{self.func}' {kwargs}")
            try: return func(**kwargs).execute()
            except Exception as error: self.handle_yt_errors(error, 'execute_yt_request', ignore_errors)


    def chunk_yt_request(self, request):    # uses the "next_chunk" thing for uploading
        self.attempts = 1
        while True:
            debug(f"(d) Chunking a YouTube upload request: '{self.func}' {request}")
            try:
                status, response = request.next_chunk()
                try: debug(f"(d) Chunk status and response: {status} {response.get('id')}, {response.get('publishedAt')}")
                except: debug(f'(d) Chunk status and response: {status}, None')
                return status, response
            except Exception as error:
                status = self.handle_yt_errors(error, 'chunk_yt_request')
                if status == -1.9:
                    print(f'\n\n\n(u) Quota reached, skipping upload process to finish cycle.')
                    return -1.9, None


    ###########################################################################


    def get_channel_videos(self):   # get list of all channel uploads (now uses direct HTTP)
        self.func = 'get_channel_videos'
        debug(f'(d) Getting list of channel videos (direct HTTP)...')
        api_key = self.API_KEY
        # Get uploads playlist id using the client library (since this is account-specific)
        response = self.execute_yt_request(self.youtube.channels().list, dict(id=CHANNEL_ID, part="contentDetails"))
        playlist_id = response['items'][0]['contentDetails']['relatedPlaylists']['uploads']

        url = "https://www.googleapis.com/youtube/v3/playlistItems"
        params = {
            "part": "snippet",
            "playlistId": playlist_id,
            "maxResults": 50,
            "key": api_key
        }
        videos = []
        page = 1
        while True:
            debug(f"(d) Requesting page {page} with params: {params}")
            resp = requests.get(url, params=params)
            debug(f"(d) Status code: {resp.status_code}")
            if resp.status_code != 200:
                print("Error:", resp.text)
                break
            data = resp.json()
            items = data.get("items", [])
            debug(f"(d) Fetched {len(items)} items")
            videos.extend(items)
            next_token = data.get("nextPageToken")
            if not next_token:
                break
            params["pageToken"] = next_token
            page += 1

        if DEBUG_MODE:
            videoId_list = [v['snippet']['resourceId']['videoId'] for v in videos]
            print(f"(d) Returning list of channel videos: {videoId_list}")
        print(len(videos))
        return videos                                   # return the list of videos



    def get_disliked_videos(self):                      # get list of disliked channel videos
        self.func = 'get_disliked_videos'
        debug(f'\n(d) Getting list of disliked videos...')
        disliked = []                                   # create empty list for storing disliked videos

        for video in self.channel_videos:               # go through all videos
            vid_id = video['snippet']['resourceId']['videoId']
            vid = self.execute_yt_request(self.youtube.videos().getRating, dict(id=vid_id))     # check the rating on the video
            rating = vid["items"][0]['rating']
            if rating == 'dislike':  # if its dislike then add it to the list
                debug(f'(d) Adding videoID {vid_id} to disliked list...')
                disliked.append(vid_id)
        debug(f'(d) Returning list of disliked videos: {disliked}')
        return disliked                                 # return the list



    def get_duplicate_videos(self, video_title, playlist_id):                      # get list of duplicate videos
        self.func = 'get_duplicate_videos'
        debug(f'\n(d) Getting list of duplicate videos...')
        duplicates = []
        next_page_token = None      # empty variable to store the next page token to access more videos

        while True:                 # Only look at 100 at a time
            debug(f'(d) Loading next page of channel videos...')
            response = self.execute_yt_request(self.youtube.playlistItems().list, dict(
                playlistId=playlist_id,
                part='snippet',
                maxResults=109,
                pageToken=next_page_token
            ))  # request all videos in playlist
            for item in response["items"]:
                # Check if video title matches the search title (case-insensitive)
                if item["snippet"]["title"].lower() == video_title.lower():
                    #debug(f'\n(d) found a duplicate video named ' + video_title)
                    duplicates.append(item["snippet"]["resourceId"]["videoId"])
            next_page_token = response.get('nextPageToken') # get next page token
            if next_page_token is None:                 # if there is no next page break the loop
                break
        return duplicates



    def check_if_video_liked_by_me(self, videoId):   # check if I liked a video
        self.func = 'check_if_video_liked_by_me'
        debug(f'(d) Checking if I liked video {videoId}')
        try:
            response = self.execute_yt_request(self.youtube.videos().getRating, dict(id=videoId))
            if response['items'][0]['rating'] == 'like':
                debug(f'(d) Video {videoId} was liked by me')
                return True
            return False
        except Exception as error:
            debug('\n(d)', type(error), error)
            print('check_if_video_liked_by_me raised the following error:', error)
            return False

    def like_video(self, videoId):    # like a video
        self.func = 'like_video'
        debug(f'(d) Liking video {videoId}')
        try:
            response = self.execute_yt_request(self.youtube.videos().getRating, dict(id=videoId))
            current_rating = response['items'][0]['rating']
            if current_rating != 'like':
                self.execute_yt_request(self.youtube.videos().rate, dict(id=videoId, rating='like'))
                print(f'Video {videoId} was successfully liked.')
                return True
            else:
                debug(f'(d) Video {videoId} was already liked by me')
                return True
        except Exception as error:
            debug('\n(d)', type(error), error)
            print('like_video raised the following error:', error)
            return False

    def extract_featured_artists(self, description_text):    # extract featured artists from description text
        self.func = 'extract_featured_artists'
        debug(f'(d) Extracting featured artists from description')
        featured_artists = []
         
        lines = description_text.split('\n')
        for line in lines:
            line_stripped = line.strip()
            if not line_stripped:
                continue
             
            if line_stripped.startswith('written') or line_stripped.startswith('Midjourney'):
                continue
             
            if ' by ' in line_stripped:
                parts = line_stripped.split(' by ')
                if len(parts) >= 2:
                    artist_part = parts[-1].strip()
                    artist_part = artist_part.split('(')[0].strip()  # Remove URL in parentheses
                     
                    if artist_part and artist_part.lower() != DISPLAY_NAME:
                        if artist_part not in featured_artists:
                            featured_artists.append(artist_part)
                            debug(f'(d) Found featured artist: {artist_part}')
         
        return featured_artists

    def get_comment_body(self, videoId):    # retrieves body of the most recent comment on the given video
        self.func = 'get_comment_body'
        debug(f'(d) Getting most recent comment from {videoId}')
        try:                                # retrieve most recent comment on a video
            response = self.execute_yt_request(self.youtube.commentThreads().list, dict(part="snippet", videoId=videoId))
            for item in response['items']:
                author = item['snippet']['topLevelComment']['snippet']['authorDisplayName'].lower()
                print(f'Comment author: {author} <{author == DISPLAY_NAME}>')
                if author == DISPLAY_NAME:
                    return item['snippet']['topLevelComment']['snippet']['textDisplay']     # return the body of the comment
            return ''       # return nothing if no comment was made by the correct user
        except Exception as error:
            debug('\n(d)', type(error), error)
            print('get_comment_body raised the following error:', error)
            return ''



    def check_for_likes_and_comments(self):                     # check for likes and comments
        self.func = 'check_for_likes_and_comments'
        debug(f'(d) Checking channel for new likes and comments...')
        for video in self.channel_videos:                       # go through all videos
            print(video)
            videoTitle = video['snippet']['title']
            videoID = video['snippet']['resourceId']['videoId']

            self.cur.execute('''
                             SELECT
                             likeCount, commentCount, used, title, credits
                             FROM videos WHERE
                             videoId=?
                             ''',
                             (videoID,))  # find video in database
            videoInfo = self.cur.fetchone()                     # fetch the info
            print('\nvideoInfo from database:', videoID, videoInfo)

            print('Checking video for likes and comments:', videoID, videoTitle)
            likeCount = 0
            commentCount = 0
            response = self.execute_yt_request(self.youtube.videos().list, dict(
                part="id,  statistics", id=videoID
            ))                                                  # request video stats

            try:
                commentCount = int(response['items'][0]['statistics']['commentCount'])
                likeCount = int(response['items'][0]['statistics']['likeCount'])
            except: pass

            if videoInfo is not None:                           # if it is already in the db
                dbVideoLikes, dbCommentCount, dbVideoUsed, dbTitle, dbCredits = videoInfo
                if dbVideoUsed == 0:                            # if it hasn't been used
                    debug(
                        f'(d) Checking "{videoTitle}":\n  '
                        f'{likeCount} current likes, {dbVideoLikes} likes in database | '
                        f'{commentCount} current comments, {dbCommentCount} comments in database.'
                    )
                    if dbCommentCount != commentCount:         # check if the comment count has changed
                        if dbCommentCount < commentCount:      # check if it has risen
                            if self.comment_titleIdBody[0] == '':
                                self.comment_titleIdBody = [videoTitle, videoID, self.get_comment_body(videoID)]   # choose this video
                        self.cur.execute(                       # update the table
                            "UPDATE videos SET commentCount=:commentCount WHERE videoId=:id",
                            {
                                'id': videoID,
                                'commentCount': commentCount
                            }
                        )
                        self.conn.commit()                      # save the data
                    if dbVideoLikes != likeCount:               # check if the comment count has changed
                        if dbVideoLikes < likeCount:            # check if it has risen

                            # check if you were the one to like it and a video hasn't already been chosen
                            response = self.execute_yt_request(self.youtube.videos().getRating, dict(id=videoID))
                            if response['items'][0]['rating'] == 'like' and self.like_titleId[0] == '':
                                self.like_titleId = [videoTitle, videoID]

                        self.cur.execute(                       # update the table
                            "UPDATE videos SET likeCount=:likeCount WHERE videoId=:id",
                            {
                                'id': videoID,
                                'likeCount': likeCount
                            }
                        )
                        self.conn.commit()                      # save the data

            else:                                               # if the video is not already in database, add it
                print('VIDEO NOT IN DATABASE\n')

                videoDescription = video['snippet']['description']
                credits = [c for c in CREDITS.values() if c in videoDescription]
                self.cur.execute("INSERT INTO videos VALUES (?, ?, ?, 0, '', 1, ?, ?)",
                                 (videoID, likeCount, commentCount, videoTitle, ';&;'.join(credits)))
                self.conn.commit()                              # save the data

                if commentCount > 0 and self.comment_titleIdBody[0] == '':                              # if comments are present and no video has been chosen yet...
                    self.comment_titleIdBody = [videoTitle, videoID, self.get_comment_body(videoID)]    # ...choose this video
                if likeCount > 0 and self.like_titleId[0] == '':                                        # if likes are present and no video has been chosen yet...
                    self.like_titleId = [videoTitle, videoID]                                           # ...choose this video
            if self.comment_titleIdBody[0] != '': return
            if self.like_titleId[0] != '': return


    def upload_videos(self):
        self.func = 'upload_videos'
        upload_conn = sqlite3.connect(os.path.join(CWD, 'videos_info.db'))  # threads require their own connections
        upload_cur = upload_conn.cursor()

        upload_cur.execute('SELECT * FROM videos WHERE deleted=0')          # get list of videos marked for deletion
        to_delete = upload_cur.fetchall()
        invalid_paths = [video[4] for video in to_delete]

        for entry in os.scandir(VIDEOS_PATH):                               # go through the contents of the folder
            debug('(d)', entry)
            if entry.is_file() and entry.path not in invalid_paths:         # if its a file and isn't marked for deletion
                title = entry.name
                isVideo = False
                for extension in (".mp4", ".mkv", ".m4v"):                  #NOT mov
                    print(title, extension, title.endswith(extension))
                    if title.endswith(extension):           # if file ends with the above extensions...
                        title = title.replace(extension, '')     # ...remove extension and mark as video
                        isVideo = True
                        break
                if isVideo:
                    print(f"\n(u) {entry.name} is being uploaded to Youtube as '{title}'")    # update user

                    # Get duplicate videos BEFORE uploading
                    duplicate_videos = self.get_duplicate_videos(title, USER_PLAYLIST_IDS[0])
                    
                    # Check if any duplicates were liked by me
                    should_like_new = False
                    for dup_video_id in duplicate_videos:
                        if self.check_if_video_liked_by_me(dup_video_id):
                            should_like_new = True
                            break

                    body = ''
                    credits = []
                    try:
                        with open(PROJECTS_PATH + "/" + title + '/description.txt', encoding='utf-8') as f:
                            lines = f.readlines()
                            for line in lines:
                                for artist, link in LINKS.items():
                                    if artist in line:
                                        line = line.replace("by " + artist, "by " + artist + " (" + link + ")")
                                        credits.append(line)
                                body += line                      # add credit to top of description
                    except:
                        print("Could not open description.txt")
                    body += FULL_BODY_TEXT
                    
                    # Do not modify title with featured artists; keep original title
                    upload_title = title


                    try:                                        # If reinstituting, indent this block once more
                        status = self.initialize_upload(    # start upload
                            options = {
                                "title": upload_title,
                                "description": body,
                                "category":10,
                                "privacyStatus": "public",
                                "file": entry.path,
                                "keywords": None
                            },
                            title = upload_title,
                            path = entry.path,
                            credits = credits,
                            upload_conn = upload_conn,
                            upload_cur = upload_cur,
                            should_like = should_like_new
                        )
                        if status == -1.9:                  # upload was skipped
                            print('\n(u) Uploading temporarily skipped.\n')
                            break
                        else:
                            debug('\n(d) Upload process complete.')
                            # After upload, get the new video ID from the database
                            upload_cur.execute("SELECT videoId FROM videos WHERE path=? ORDER BY ROWID DESC LIMIT 1", (entry.path,))
                            row = upload_cur.fetchone()
                            if row:
                                new_video_id = row[0]
                                # Remove the just-uploaded video from the duplicates list
                                if new_video_id in duplicate_videos:
                                    duplicate_videos.remove(new_video_id)
                            # Now delete only previous duplicates
                            self.delete_videos(duplicate_videos)
                    except Exception as error:
                        debug('\n(d)', type(error), error)
                        print('Upload attempt on', entry, 'failed with the following error:', error)
        upload_conn.close()                                 # close thread's database connection
        return



    # https://developers.google.com/youtube/v3/guides/uploading_a_video
    def initialize_upload(self, options, title, path, credits, upload_conn, upload_cur, should_like=False):
        self.func = 'initialize_upload'
        print('Initializing upload...\n')
        tags = None
        if options["keywords"]: # check if there are any key words
            tags = options.keywords.split(",") # create a list of keywords
        body = dict(            # dictionary with video info
            snippet = dict(
                title = options["title"],                   # title option
                description = options["description"],       # descritption
                tags = tags,                                # tags
                categoryId = options["category"]            # category
            ),
            status = dict(
                privacyStatus = options["privacyStatus"]    # privacy status
            )
        )

        # Call the API's videos.insert method to create and upload the video.
        insert_request = self.get_yt_request(self.youtube.videos().insert, dict(
            part = ','.join(body.keys()),   # add the video info
            body = body,
            media_body = MediaFileUpload(options["file"], chunksize=-1, resumable=True)     # upload
        ))

        # This method implements an exponential backoff strategy to resume a failed upload.
        # https://www.youtube.com/playlist?list=PLS0ekF80gz5_33_ejo17jNDPUZS_OAG2Q
        # https://www.youtube.com/playlist?list=PLFvnUARoyeJzeEfOZkOf9iPifGghOmhMJ
        response = None
        while response is None:                                         # while a response is not posted
            print("(u) Uploading video...")
            status, response = self.chunk_yt_request(insert_request)    # update status and response
            if status == -1.9:                                          # upload-skip code -> end immediately
                return status

            if response is not None:
                if 'id' in response:                                    # if an id was returned, upload was successful
                    videoID = response['id']
                    print(f"\n(u) Video id '{videoID}' was successfully uploaded.")
                    upload_cur.execute('INSERT INTO videos VALUES (?,0,0,0,?,0,?,?)',
                                       (videoID, path, title, ';&;'.join(credits)))
                    upload_conn.commit()                                # add video to database and save entry
                    print(f"(u) Video added to database.")

                    for user_playlist_id in USER_PLAYLIST_IDS:          # attempt to insert into user playlists
                        try:
                            response = self.execute_yt_request(self.youtube.playlistItems().insert, dict(
                                part = "snippet",
                                body = {
                                    "snippet": {
                                        "playlistId": user_playlist_id,
                                        "position": 0,
                                        "resourceId": {
                                            "kind": "youtube#video",
                                            "videoId": response['id']
                                        }
                                    }
                                }
                            ), ignore_errors = True)                    # really ugly right here but oh well
                        except googleapiclient.errors.HttpError as e:
                            print("Attempt to insert video into playlist MAY have failed with error:", e)
                            return

                    if should_like:
                        print("(u) Old duplicate was liked, liking new video...")
                        self.like_video(videoID)

                else:
                    print(f" The upload failed with an unexpected response:", response)
                    return


    def delete_associated_files(self, video_title):
        ''' Delete .wav file and project folder associated with a disliked video '''
        audio_works_path = r"D:\[Library]\[Audio]\[Works]"
        projects_path = r"D:\[Library]\[Audio]\[Works]\[Projects]"
        
        # Look for .wav file
        wav_file = os.path.join(audio_works_path, f"{video_title}.wav")
        if os.path.exists(wav_file):
            try:
                send2trash(wav_file)
                print(f"Found and sent to recycle bin: {wav_file}")
            except Exception as error:
                print(f"Failed to send .wav file to recycle bin: {wav_file} - {error}")
        else:
            print(f".wav file not found: {wav_file}")
        
        # Look for project folder
        project_folder = os.path.join(projects_path, video_title)
        if os.path.exists(project_folder):
            try:
                send2trash(project_folder)
                print(f"Found and sent to recycle bin: {project_folder}")
            except Exception as error:
                print(f"Failed to send project folder to recycle bin: {project_folder} - {error}")
        else:
            print(f"Project folder not found: {project_folder}")



    def delete_videos(self, disliked_videos, delete_local_files=False):                 # Delete videos from playlists, then the channel
        self.func = 'delete_videos'

        # Get a list of playlist items from all playlists and delete any that were disliked
        if disliked_videos:                                 # if disliked videos detected
            print('Deleting videos...')
            for user_playlist_id in USER_PLAYLIST_IDS:      # check every playlist
                try:
                    print('Checking user_playlist for videos to delete:', user_playlist_id)

                    # Sort by every <maxResults> results
                    playlistItems = []                      # create empty list to store the videos
                    next_page_token = None                  # empty variable to store the next page token to access more videos

                    while True:                             # Only look at 100 at a time
                        debug(f'(d) Loading next page of playlist {user_playlist_id}...')
                        response = self.execute_yt_request(self.youtube.playlistItems().list, dict(
                            playlistId=user_playlist_id,
                            part='contentDetails',
                            maxResults=100,
                            pageToken=next_page_token
                        ))                                  # request all uploads
                        playlistItems += response['items']  # add videos to list
                        next_page_token = response.get('nextPageToken')  # get next page token
                        if next_page_token is None:         # if there is no next page break the loop
                            break

                    for item in playlistItems:
                        try:
                            print('Checking playlist item', item['contentDetails'])
                            playlistItemID = item['id']     # unique playlist-specific id for video
                            videoID = item['contentDetails']['videoId']       # video's original id
                            if videoID in disliked_videos:
                                print('\nDeleting from playlist:', videoID)
                                self.execute_yt_request(self.youtube.playlistItems().delete, dict(id=playlistItemID))
                                print('Successfully deleted from playlist.\n')
                        except Exception as error:
                            debug('\n(d)', type(error), error)
                            print('playlistItem raised the following error:', item, error)
                except Exception as error:
                    debug('\n(d)', type(error), error)
                    print('Playlist raised the following error:', user_playlist_id, error)

        # Actually delete videos from YouTube AFTER removing them from playlists
        for vID in disliked_videos:
            try:
                print('\nDeleting video id from YouTube:', vID)
                self.execute_yt_request(self.youtube.videos().delete, dict(id=vID))   # delete video
                print('Deleted.\n')
                
                # Get video title from channel_videos and delete associated files
                for video in self.channel_videos:
                    if video['snippet']['resourceId']['videoId'] == vID:
                        video_title = video['snippet']['title']
                        print(f'Checking for associated files for: {video_title}')
                        self.delete_associated_files(video_title)
                        break
            except Exception as error:
                debug('\n(d)', type(error), error)
                print('Video-deletion attempt failed with the following error:', vID, error)



bot = UploadBot()
bot.run()
